# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "golang.org/x/tools"
        versions: ["<0.5.0"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

