builds:
  - goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "main.version=v{{.Version}}"
    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
