project_name: kirke

release:
  github:
    owner: magicdrive
    name: kirke
  draft: false
  prerelease: "false"

builds:
  - id: kirke
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w -X "main.version=v{{.Version}}"
    env:
      - CGO_ENABLED=0
    binary: kirke
    main: ./main.go

archives:
  - id: tar.gz
    format: tar.gz
    files:
     - src: misc/completions/kirke-completion.sh
       dst: completions/kirke-completion.sh
     - src: misc/completions/zsh/_kirke
       dst: completions/zsh/_kirke
     - src: misc/completions/bash/kirke-completion.bash
       dst: completions/bash/kirke-completion.bash

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

brews:
  - name: kirke
    repository:
      owner: magicdrive
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/magicdrive/kirke"
    description: "Yet another command-line tool for converting JSON strings into Golang struct definitions."
    license: "MIT"
    ids: [tar.gz]
    install: |
      bin.install "kirke"
    extra_install: |
      bash_completion.install "completions/bash/kirke-completion.bash" => "kirke"
      zsh_completion.install "completions/zsh/_kirke" => "_kirke"
    test: |
      system "#{bin}/kirke", "--version"
    commit_author:
      name: magicdrive bot
      email: hiroshi.ikegami+githubbot@magicdrive.jp

